export const MODELS = {
  club: "x_club",
  game: "x_game",
  gameAttendance: "x_game_attendance",
  gameEvent: "x_game_event",
  team: "x_team",
  teamStaff: "x_team_staff",
  tournament: "x_tournament",
  player: "x_player",
  playerGameStat: "x_player_game_stat",
} as const;

export const GAME = {
  active: "x_active",
  name: "x_name",
  awayScore: "x_studio_away_score",
  awayTeam: "x_studio_away_team",
  datetime: "x_studio_datetime",
  homeScore: "x_studio_home_score",
  homeTeam: "x_studio_home_team",
  location: "x_studio_location",
  matchName: "x_studio_match_name",
  awayTeamFouls: "x_studio_away_team_fouls",
  awayTimeouts: "x_studio_away_timeouts",
  gameClockSeconds: "x_studio_game_clock_seconds",
  homeTeamFouls: "x_studio_home_team_fouls",
  homeTimeouts: "x_studio_home_timeouts",
  period: "x_studio_period",
  possessionTeam: "x_studio_possession_team",
  shotClockSeconds: "x_studio_shot_clock_seconds",
  stats: "x_studio_stats",
  status: "x_studio_status",
  websiteDescription: "x_studio_website_description",
  week: "x_studio_week",
  refereeName: "x_studio_referee",
  refereeAssistant: "x_studio_referee_2",
  referee3: "x_studio_referee_3",
  scorekeeper: "x_studio_scorekeeper",
  scorekeeper2: "x_studio_scorekeeper_2",
  awayPresent: "x_studio_away_present",
  homePresent: "x_studio_home_present",
  equalizationPoints: "x_studio_equalization_points",
  equalizationTeam: "x_studio_equalization_team",
  equalizationApplied: "x_studio_equalization_applied",
  attendanceIds: "x_studio_attendance_ids",
} as const;

export const TEAM = {
  active: "x_active",
  gamesPlayed: "x_games_played",
  losses: "x_losses",
  name: "x_name",
  assistantCoach2: "x_studio_assistant_coach_2",
  assistantCoach: "x_studio_assitant_coach",
  awayGames: "x_studio_away_games",
  category: "x_studio_categoria",
  club: "x_studio_club_id",
  coachCertificate: "x_studio_certificado_coach",
  coach: "x_studio_coach",
  contact: "x_studio_contact",
  homeGames: "x_studio_home_games",
  image: "x_studio_image",
  players: "x_studio_players",
  sequence: "x_studio_sequence",
  gender: "x_studio_sexo",
  tournament: "x_studio_tournament",
  winPct: "x_win_pct",
  wins: "x_wins",
} as const;

export const TEAM_STAFF = {
  name: "x_name",
  role: "x_studio_role",
  team: "x_studio_team_id",
} as const;

// Team colors are defined on the Club (x_club), shared by every team in that club,
// and reached from a team via TEAM.club. Stored as hex char fields.
export const CLUB = {
  name: "x_name",
  image: "x_studio_image",
  logoFilename: "x_studio_logo_filename",
  primaryColor: "x_studio_primary_color", // "Color de Camisa" (shirt) — main identity color
  secondaryColor: "x_studio_secondary_color", // "Color de Letra" (text on shirt)
  accentColor: "x_studio_accent_color", // "Color de Pantalon" (pants)
} as const;

export const PLAYER = {
  active: "x_active",
  avatar: "x_avatar_image",
  name: "x_name",
  dateOfBirth: "x_studio_date_of_birth",
  school: "x_studio_escuela",
  grade: "x_studio_grade",
  age: "x_studio_integer_field_7h_1jf1916jk",
  jerseyNumber: "x_studio_jersey_number",
  position: "x_studio_position",
  shirtSize: "x_studio_size_camisa",
  shortsSize: "x_studio_size_pantalon_1",
  stats: "x_studio_stats",
  team: "x_studio_team",
  totalPoints: "x_total_points",
} as const;

export const PLAYER_STAT = {
  active: "x_active",
  name: "x_name",
  assists: "x_studio_assists",
  blocks: "x_studio_blocks",
  defensiveRebounds: "x_studio_def_rebounds",
  fouls: "x_studio_fouls",
  techFouls: "x_studio_tech_fouls",
  freeThrowsAttempted: "x_studio_fta",
  freeThrowsMade: "x_studio_ftm",
  game: "x_studio_game",
  overtime: "x_studio_ot",
  offensiveRebounds: "x_studio_off_rebounds",
  player: "x_studio_player",
  q1: "x_studio_q1",
  q2: "x_studio_q2",
  q3: "x_studio_q3",
  q4: "x_studio_q4",
  team: "x_studio_related_field_7hr_1jf0tn6sg",
  threePointersAttempted: "x_studio_3pa",
  threePointersMade: "x_studio_3pm",
  totalPoints: "x_studio_total_points",
  turnovers: "x_studio_turnovers",
  twoPointersAttempted: "x_studio_2pa",
  twoPointersMade: "x_studio_2pm",
  steals: "x_studio_steals",
  websiteDescription: "x_studio_website_description",
} as const;

export const GAME_EVENT = {
  active: "x_active",
  actionType: "x_studio_action_type",
  clockSeconds: "x_studio_clock_seconds",
  game: "x_studio_game",
  name: "x_name",
  note: "x_studio_note",
  period: "x_studio_period",
  player: "x_studio_player",
  points: "x_studio_points",
  scoreAfter: "x_studio_score_after",
  shotValue: "x_studio_shot_value",
  shotX: "x_studio_shot_x",
  shotY: "x_studio_shot_y",
  shotZone: "x_studio_shot_zone",
  team: "x_studio_team",
  issuedByRef: "x_studio_issued_by_ref",
} as const;

export const ATTENDANCE = {
  active: "x_active",
  name: "x_name",
  game: "x_studio_game",
  player: "x_studio_player",
  team: "x_studio_team",
  present: "x_studio_present",
  starter: "x_studio_starter",
  jersey: "x_studio_jersey",
} as const;

export const GAME_FIELDS = [
  "id",
  "display_name",
  GAME.name,
  GAME.awayScore,
  GAME.awayTeam,
  GAME.datetime,
  GAME.homeScore,
  GAME.homeTeam,
  GAME.location,
  GAME.matchName,
  GAME.status,
  GAME.week,
] as const;

export const GAME_OPTIONAL_FIELDS = [
  GAME.awayTeamFouls,
  GAME.awayTimeouts,
  GAME.gameClockSeconds,
  GAME.homeTeamFouls,
  GAME.homeTimeouts,
  GAME.period,
  GAME.possessionTeam,
  GAME.shotClockSeconds,
  GAME.refereeName,
  GAME.refereeAssistant,
  GAME.referee3,
  GAME.scorekeeper,
  GAME.scorekeeper2,
  GAME.awayPresent,
  GAME.homePresent,
  GAME.equalizationPoints,
  GAME.equalizationTeam,
  GAME.equalizationApplied,
] as const;

export const TEAM_FIELDS = [
  "id",
  "display_name",
  TEAM.name,
  TEAM.club,
  TEAM.gamesPlayed,
  TEAM.losses,
  TEAM.category,
  TEAM.coach,
  TEAM.gender,
  TEAM.image,
  TEAM.sequence,
  TEAM.winPct,
  TEAM.wins,
] as const;

export const TEAM_STAFF_FIELDS = [
  "id",
  "display_name",
  TEAM_STAFF.name,
  TEAM_STAFF.role,
  TEAM_STAFF.team,
] as const;

export const CLUB_FIELDS = [
  "id",
  "display_name",
  CLUB.name,
  CLUB.image,
  CLUB.logoFilename,
  CLUB.primaryColor,
  CLUB.secondaryColor,
  CLUB.accentColor,
] as const;

export const PLAYER_FIELDS = [
  "id",
  "display_name",
  PLAYER.active,
  PLAYER.avatar,
  PLAYER.name,
  PLAYER.grade,
  PLAYER.jerseyNumber,
  PLAYER.position,
  PLAYER.team,
  PLAYER.totalPoints,
] as const;

export const PLAYER_STAT_FIELDS = [
  "id",
  "display_name",
  PLAYER_STAT.active,
  PLAYER_STAT.name,
  PLAYER_STAT.fouls,
  PLAYER_STAT.game,
  PLAYER_STAT.overtime,
  PLAYER_STAT.player,
  PLAYER_STAT.q1,
  PLAYER_STAT.q2,
  PLAYER_STAT.q3,
  PLAYER_STAT.q4,
  PLAYER_STAT.team,
  PLAYER_STAT.totalPoints,
] as const;

export const PLAYER_STAT_OPTIONAL_FIELDS = [
  PLAYER_STAT.assists,
  PLAYER_STAT.blocks,
  PLAYER_STAT.defensiveRebounds,
  PLAYER_STAT.techFouls,
  PLAYER_STAT.freeThrowsAttempted,
  PLAYER_STAT.freeThrowsMade,
  PLAYER_STAT.offensiveRebounds,
  PLAYER_STAT.steals,
  PLAYER_STAT.threePointersAttempted,
  PLAYER_STAT.threePointersMade,
  PLAYER_STAT.turnovers,
  PLAYER_STAT.twoPointersAttempted,
  PLAYER_STAT.twoPointersMade,
] as const;

export const GAME_EVENT_FIELDS = [
  "id",
  "display_name",
  GAME_EVENT.actionType,
  GAME_EVENT.clockSeconds,
  GAME_EVENT.game,
  GAME_EVENT.name,
  GAME_EVENT.note,
  GAME_EVENT.period,
  GAME_EVENT.player,
  GAME_EVENT.points,
  GAME_EVENT.scoreAfter,
  GAME_EVENT.shotValue,
  GAME_EVENT.shotX,
  GAME_EVENT.shotY,
  GAME_EVENT.shotZone,
  GAME_EVENT.team,
  GAME_EVENT.issuedByRef,
] as const;

export const ATTENDANCE_FIELDS = [
  "id",
  "display_name",
  ATTENDANCE.active,
  ATTENDANCE.name,
  ATTENDANCE.game,
  ATTENDANCE.player,
  ATTENDANCE.team,
  ATTENDANCE.present,
  ATTENDANCE.starter,
  ATTENDANCE.jersey,
] as const;
